# -*- coding: utf-8 -*-
"""ai.labsheet4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0DdcmQECZq-q0bKs_RelOQhyx3Ef4QQ
"""

import pandas as pd
 df = pd.read_csv("/content/German_Credit_Card_Dataset (6).csv")
 df.info()
 df.shape
 df.head()

df.iloc[0:5,0:7]

df.iloc[0:5, 7:15]

df.iloc[0:5, 7:15]

df['checkin_acc'].unique()

X_features = list(df.columns)
 X_features.remove('status')
 encoded_df = pd.get_dummies(df[X_features],drop_first=True)
 print(list(encoded_df.columns))

X = encoded_df
 Y = df['status']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size = 0.3, random_state = 42)

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion = 'gini', max_depth = 3)
clf.fit(X_train, y_train)

pred_y = clf.predict(X_test)

from sklearn import metrics
print("Confusion Matrix is\n",metrics.confusion_matrix(pred_y, y_test))
print("Accuracy is", metrics.accuracy_score(pred_y,y_test))
print("AUC Score is", metrics.roc_auc_score(pred_y, y_test))

from sklearn.tree import export_graphviz
import pydotplus as pdot
from IPython.display import Image
export_graphviz(clf,out_file = "tree.odt", feature_names = X_train.columns, filled = True)
graph = pdot.graphviz.graph_from_dot_file("tree.odt")
graph.write_jpg("tree.png")
Image(filename = "tree.png")