# -*- coding: utf-8 -*-
"""labsheet1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s3niJHN3HDHitxZiMHLJFyXhoGyDX97m
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

cars_data = pd.read_csv("/content/Toyota.csv")

cars_data.dropna(axis=0,inplace=True)
cars_data

plt.scatter(cars_data['Age'],cars_data['Price'],color = 'blue')
plt.title('Scatter plot of price vs Age')
plt.xlabel('Age(month)')
plt.ylabel('price(Euros)')
plt.show()

plt.hist(cars_data['KM'])

plt.hist(cars_data['KM'],color='green',edgecolor='white',bins=30)

plt.title('Histogram of KM')

plt.xlabel('Kilometers')

plt.ylabel('Frequency')

plt.show()

counts = [979, 120, 2]

fueltype = ('Petrol', 'Diesel', 'CNG')

index = np.arange(len(fueltype))

plt.bar(index, counts,color=['red','blue','cyan'])

plt.title('Bar plot of fuel type')

plt.xlabel('Fuel Types')

plt.ylabel('frequency')

plt.xticks(index, fueltype, rotation = 60)

plt.show

x = np.linspace(0, 5, 10)

fig, axes = plt.subplots(1, 2, figsize=(10,4))

axes[0].plot(x, x**2, x, np.exp(x))



axes[0].set_title("Normal scale")

axes[1].plot(x, x**2, x, np.exp(x))

axes[1].set_yscale("log")

axes[1].set_title("logarithmic scale (y)");

fig, ax = plt.subplots(figsize=(10, 4))
ax.plot(x,  x**2, x,  x**3, lw=2)
ax.set_xticks([1, 2, 3, 4, 5])
ax.set_xticklabels([r'$\alpha$', r'$\beta$', r'$\gamma$', r'$\delta$', r'$\epsilon$'], fontsize=18)
yticks = [0, 50, 100, 150]
ax.set_yticks(yticks)
ax.set_yticklabels(["$%.1f$" % y for y in yticks], fontsize=18); #use LaTeX formatted labels

fig, ax1 = plt.subplots()
ax1.plot(x, x**2, lw=2, color="blue")
ax1.set_ylabel(r"area $(m^2)$", fontsize=18, color="blue")
for label in ax1.get_yticklabels():
  label.set_color("blue")
ax2 = ax1.twinx()
ax2.plot(x, x**3, lw=2, color="red")
ax2.set_ylabel(r"volume $(m^3)$", fontsize=18, color="red")
for label in ax2.get_yticklabels():
  label.set_color("red")

xx = np.linspace(-0.75, 1., 100)
n = np.array([0, 1, 2, 3, 4, 5])
fig, axes = plt.subplots(1, 4, figsize=(12,3))
axes[0].scatter(xx, xx + 0.25*np.random.randn(len(xx)))
axes[0].set_title("scatter")
axes[1].step(n, n**2, lw=2)
axes[1].set_title("step")
axes[2].bar(n, n**2, align="center", width=0.5, alpha=0.5)
axes[2].set_title("bar")
axes[3].fill_between(x, x**2, x**3, color="green",alpha=0.5);