# -*- coding: utf-8 -*-
"""labsheet3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-71lQqMIC9NAmLbnUnxaZ_gfK_-OFpv
"""

import numpy as np
 import pandas as pd
 import matplotlib.pyplot as plt
 import seaborn as sns

df = pd.read_csv("/content/advertising.ai.csv")
print(df)

df.head(10)
 df.info()
 print(df.shape)

print(df.describe())

fig, axs = plt.subplots(3, figsize = (5,5))
plt1 = sns.boxplot(df['TV'], ax=axs[0])
plt2 = sns.boxplot(df['Newspaper'], ax = axs[1])
plt3 = sns.boxplot(df['Radio'], ax = axs[2])
plt.tight_layout()

X = df['TV']
 y = df['Sales']
 # Plot scatter plot between X and y
 plt.scatter(X, y, color = 'blue', label='Scatter Plot')
 plt.title('Relationship between TV and Sales')
 plt.xlabel('TV')
 plt.ylabel('Sales')
 plt.legend()
 plt.show()

# Print the dimensions of X and y
 print(X.shape)
 print(y.shape)

X=np.array(X)
 y=np.array(y)

X = X.reshape(-1,1)
y = y.reshape(-1,1)

print(X.shape)
 print(y.shape)

from sklearn.model_selection import train_test_split
 X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.30, random_state=42)
 # Print the dimensions of X_train,X_test,y_train,y_test
 print(X_train.shape)
 print(y_train.shape)
 print(X_test.shape)
 print(y_test.shape)

from sklearn.linear_model import LinearRegression

lm = LinearRegression()

lm.fit(X_train,y_train)

y_pred=lm.predict(X_test)

plt.scatter(X_train, y_train, color = 'red')
 plt.plot(X_train, lm.predict(X_train), color = 'blue')
 # Visualising the Test set results
 plt.scatter(X_test, y_test, color = 'red')
 plt.plot(X_test, lm.predict(X_test), color = 'blue')
 plt.title('Test set results')
 plt.xlabel('TV')
 plt.ylabel('Sales')
 plt.show()
 # Compute model slope and intercept
 slope = lm.coef_
 intercept = lm.intercept_,
 print("Estimated model slope:" , slope)
 print("Estimated model intercept:" , intercept)

X_new = [[200]]
 lm.predict(X_new)

